### ISSUE TITLE
How to run this script on MAC?

### ISSUE THREAD

**Issue by rishabh-ojha98** [hcmlab/vadnet#14]
I tried to run the script on MacOS and encountered following error.
Please help me as i'm new to MacOS.
### Traceback (most recent call last):
  File "vad_extract.py", line 138, in <module>
    extract_voice(args.model, args.files, n_batch=args.n_batch)
  File "vad_extract.py", line 55, in extract_voice
    if not all([os.path.exists(checkpoint_path + x) for x in ['.data-00000-of-00001', '.index', '.meta']]):
  File "vad_extract.py", line 55, in <listcomp>
    if not all([os.path.exists(checkpoint_path + x) for x in ['.data-00000-of-00001', '.index', '.meta']]):
NameError: free variable 'checkpoint_path' referenced before assignment in enclosing scope

**Comment by shelm** [comment]
This error occurs when the passed path is a valid folder but have no checkpoints to load in it. 
What's the value of the _path_-parameter in the _extract_voice_ function? 
Be aware that most parts of the project are windows only.
You may use some of the provided python scripts for your inspiration or as code templates but you won't be able to run the whole pipeline on you Mac.

**Comment by gilgameshskytrooper** [comment]
I would also like the ability to run this on linux as well. It would be super cool if you guys created a Dockerfile that does the equivalent commands found in do_bin.cmd, and sets up a linux instance (running inside Docker) so that people can use this inside Linux.

**Comment by nlml** [comment]
I made a fork here which should make things clearer on how to run this on mac https://github.com/nlml/vadnet
